angular.module('rapid-build').constant 'INSTALL_COMPONENTS',
	alert:      'npm install @rapid-build-ui/rb-alert'
	button:     'npm install @rapid-build-ui/rb-button'
	checkbox:   'npm install @rapid-build-ui/rb-checkbox'
	checkboxes: 'npm install @rapid-build-ui/rb-checkboxes'
	code:       'npm install @rapid-build-ui/rb-code'
	dropdown:   'npm install @rapid-build-ui/rb-dropdown'
	icon:       'npm install @rapid-build-ui/rb-icon'
	input:      'npm install @rapid-build-ui/rb-input'
	modal:      'npm install @rapid-build-ui/rb-modal'
	nav:        'npm install @rapid-build-ui/rb-nav'
	popover:    'npm install @rapid-build-ui/rb-popover'
	radios:     'npm install @rapid-build-ui/rb-radios'
	table:      'npm install @rapid-build-ui/rb-table'
	textarea:   'npm install @rapid-build-ui/rb-textarea'
	textcurve:  'npm install @rapid-build-ui/rb-textcurve'
	toggle:     'npm install @rapid-build-ui/rb-toggle'