angular.module('rapid-build').constant 'INSTALL_COMPONENTS',
	alert:      'yarn add @rapid-build-ui/rb-alert'
	button:     'yarn add @rapid-build-ui/rb-button'
	checkbox:   'yarn add @rapid-build-ui/rb-checkbox'
	checkboxes: 'yarn add @rapid-build-ui/rb-checkboxes'
	code:       'yarn add @rapid-build-ui/rb-code'
	dropdown:   'yarn add @rapid-build-ui/rb-dropdown'
	icon:       'yarn add @rapid-build-ui/rb-icon'
	input:      'yarn add @rapid-build-ui/rb-input'
	modal:      'yarn add @rapid-build-ui/rb-modal'
	nav:        'yarn add @rapid-build-ui/rb-nav'
	popover:    'yarn add @rapid-build-ui/rb-popover'
	radios:     'yarn add @rapid-build-ui/rb-radios'
	table:      'yarn add @rapid-build-ui/rb-table'
	textarea:   'yarn add @rapid-build-ui/rb-textarea'
	textcurve:  'yarn add @rapid-build-ui/rb-textcurve'
	toggle:     'yarn add @rapid-build-ui/rb-toggle'